services:
  job-wars:
    image: ghcr.io/larrymotalavigne/job-wars:latest
    container_name: job-wars
    restart: unless-stopped
    networks:
      - job-wars

networks:
  job-wars:
    name: job-wars
    driver: bridge
